products = [
  {
    '_id': '1',
    'name': 'Airpods Wireless Bluetooth Fones de Ouvido',
    'image': '/images/airpods.jpg',
    'description':
      'Os AirPods são controlados pelo processador W1 da Apple e utilizam sensores óticos e um acelerómetro de movimento para detetar se estão colocados nos ouvidos. Quer utilize ambos ou apenas um auricular, o processador W1 liga automaticamente o som e ativa o microfone.',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 1.104,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'iPhone 11 Pro 256GB',
    'image': '/images/phone.jpg',
    'description':
      'Descrição do Produto',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 6.419,
    'countInStock': 0,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Camera Cannon EOS 80D DSLR',
    'image': '/images/camera.jpg',
    'description':
      'Seja para elevar o nível das suas fotografias ou simplesmente para se divertir com mais recursos, a EOS 80D é uma câmera versátil ideal para levar em praticamente qualquer lugar. Apresenta 45 pontos de autofoco, todos do tipo cruzados, fornecendo velocidade e precisão em praticamente qualquer tipo de luz. Para ajudar os fotógrafos a não perderem nenhum momento, um visor inteligente com aproximadamente 100% de cobertura fornece uma visão clara e abrangente dos dados da imagem.',
    'brand': 'Cannon',
    'category': 'Electronics',
    'price': 7.660,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Sony Playstation 4 Pro Versão Branca',
    'image': '/images/playstation.jpg',
    'description':
      'Jogue os títulos de sucesso mais recentes do PS4 e os exclusivos da PlayStation na incrível resolução 4K no console PS4 Pro na sua TV 4K e transmita seu entretenimento favorito com os belíssimos detalhes visuais usando serviços compatíveis com 4K.',
    'brand': 'Sony',
    'category': 'Electronics',
    'price': 4.530,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'Mouse Gamer Logitech G-Series',
    'image': '/images/mouse.jpg',
    'description':
      'A Logitech G desenvolve premiados mouses para jogos com e sem fio. Encontre o mouse certo para você com as constantes inovações, que vão dos sensores ao formato dos mouses.',
    'brand': 'Logitech',
    'category': 'Electronics',
    'price': 296,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Amazon Echo Dot Terceira Geração',
    'image': '/images/alexa.jpg',
    'description':
      'O Echo Dot é o nosso smart speaker de maior sucesso. Controlado por voz com a Alexa, ele é perfeito para qualquer ambiente. Você pode pedir músicas, notícias, informações e muito mais. Além de ligar para amigos e familiares e controlar dispositivos compatíveis de casa inteligente com sua voz.',
    'brand': 'Amazon',
    'category': 'Electronics',
    'price': 217,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
  },
]